# Project Name
TARGET = Ouroboros

# Sources
CPP_SOURCES = Ouroboros.cpp src/OLED/OLED.cpp src/Presets/presets.cpp src/tempoManager/tempoManager.cpp src/buttonManager/buttonManager.cpp \
src/knobManager/knobManager.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP
CLOUDSEED_DIR = ../../CloudSeedCore-master

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile